2013-07-02 12:20:48.839 [error] <0.247.0> gen_server <0.247.0> terminated with reason: no function clause matching amqp_channel:build_content(<0.31.0>) line 802
2013-07-02 12:20:48.840 [error] <0.247.0> CRASH REPORT Process <0.247.0> with 0 neighbours exited with reason: no function clause matching amqp_channel:build_content(<0.31.0>) line 802 in gen_server:terminate/6 line 747
2013-07-02 12:20:48.844 [error] <0.245.0> Supervisor {<0.245.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.236.0>, 1, <0.246.0>, #Fun<amqp_channel_sup.1.46960472>) at <0.247.0> exit with reason no function clause matching amqp_channel:build_content(<0.31.0>) line 802 in context child_terminated
2013-07-02 12:20:48.846 [error] <0.245.0> Supervisor {<0.245.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.236.0>, 1, <0.246.0>, #Fun<amqp_channel_sup.1.46960472>) at <0.247.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 12:20:48.849 [error] <0.236.0> Connection (<0.236.0>) closing: internal error in channel (<0.247.0>): {function_clause,[{amqp_channel,build_content,[<0.31.0>],[{file,"src/amqp_channel.erl"},{line,802}]},{amqp_channel,handle_method_to_server,6,[{file,"src/amqp_channel.erl"},{line,536}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,588}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}

2013-07-02 13:37:23.620 [error] <0.94.0> gen_server <0.94.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.104.0>,killed}, {state,#Port<0.3625>,600,<0.100.0>,131072,undefined,false}) line 58
2013-07-02 13:37:23.622 [error] <0.94.0> CRASH REPORT Process <0.94.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.104.0>,killed}, {state,#Port<0.3625>,600,<0.100.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 13:37:23.626 [error] <0.93.0> Supervisor {<0.93.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.94.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.104.0>,killed}, {state,#Port<0.3625>,600,<0.100.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 13:37:23.628 [error] <0.93.0> Supervisor {<0.93.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.94.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 13:38:06.187 [error] <0.383.0> gen_server <0.383.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.391.0>,killed}, {state,#Port<0.3980>,600,<0.387.0>,131072,undefined,false}) line 58
2013-07-02 13:38:06.188 [error] <0.383.0> CRASH REPORT Process <0.383.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.391.0>,killed}, {state,#Port<0.3980>,600,<0.387.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 13:38:06.194 [error] <0.382.0> Supervisor {<0.382.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.383.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.391.0>,killed}, {state,#Port<0.3980>,600,<0.387.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 13:38:06.197 [error] <0.382.0> Supervisor {<0.382.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.383.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 14:39:45.642 [error] <0.423.0> gen_server <0.423.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.431.0>,killed}, {state,#Port<0.3981>,600,<0.427.0>,131072,undefined,false}) line 58
2013-07-02 14:39:45.644 [error] <0.423.0> CRASH REPORT Process <0.423.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.431.0>,killed}, {state,#Port<0.3981>,600,<0.427.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 14:39:45.650 [error] <0.422.0> Supervisor {<0.422.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.423.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.431.0>,killed}, {state,#Port<0.3981>,600,<0.427.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 14:39:45.653 [error] <0.422.0> Supervisor {<0.422.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.423.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 14:40:31.923 [error] <0.466.0> gen_server <0.466.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.474.0>,killed}, {state,#Port<0.4118>,600,<0.470.0>,131072,undefined,false}) line 58
2013-07-02 14:40:31.924 [error] <0.466.0> CRASH REPORT Process <0.466.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.474.0>,killed}, {state,#Port<0.4118>,600,<0.470.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 14:40:31.929 [error] <0.465.0> Supervisor {<0.465.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.466.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.474.0>,killed}, {state,#Port<0.4118>,600,<0.470.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 14:40:31.932 [error] <0.465.0> Supervisor {<0.465.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.466.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 14:52:56.416 [error] <0.508.0> gen_server <0.508.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.516.0>,killed}, {state,#Port<0.4188>,600,<0.512.0>,131072,undefined,false}) line 58
2013-07-02 14:52:56.417 [error] <0.508.0> CRASH REPORT Process <0.508.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.516.0>,killed}, {state,#Port<0.4188>,600,<0.512.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 14:52:56.422 [error] <0.507.0> Supervisor {<0.507.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.508.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.516.0>,killed}, {state,#Port<0.4188>,600,<0.512.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 14:52:56.425 [error] <0.507.0> Supervisor {<0.507.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.508.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 14:54:52.256 [error] <0.88.0> gen_server <0.88.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.98.0>,killed}, {state,#Port<0.3601>,600,<0.94.0>,131072,undefined,false}) line 58
2013-07-02 14:54:52.258 [error] <0.88.0> CRASH REPORT Process <0.88.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.98.0>,killed}, {state,#Port<0.3601>,600,<0.94.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 14:54:52.263 [error] <0.87.0> Supervisor {<0.87.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.88.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.98.0>,killed}, {state,#Port<0.3601>,600,<0.94.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 14:54:52.266 [error] <0.87.0> Supervisor {<0.87.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.88.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 15:11:29.527 [error] <0.133.0> gen_server <0.133.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.141.0>,killed}, {state,#Port<0.3803>,600,<0.137.0>,131072,undefined,false}) line 58
2013-07-02 15:11:29.528 [error] <0.133.0> CRASH REPORT Process <0.133.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.141.0>,killed}, {state,#Port<0.3803>,600,<0.137.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 15:11:29.533 [error] <0.132.0> Supervisor {<0.132.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.133.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.141.0>,killed}, {state,#Port<0.3803>,600,<0.137.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 15:11:29.537 [error] <0.132.0> Supervisor {<0.132.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.133.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 15:12:39.029 [error] <0.88.0> gen_server <0.88.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.98.0>,killed}, {state,#Port<0.3601>,600,<0.94.0>,131072,undefined,false}) line 58
2013-07-02 15:12:39.031 [error] <0.88.0> CRASH REPORT Process <0.88.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.98.0>,killed}, {state,#Port<0.3601>,600,<0.94.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 15:12:39.035 [error] <0.87.0> Supervisor {<0.87.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.88.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.98.0>,killed}, {state,#Port<0.3601>,600,<0.94.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 15:12:39.038 [error] <0.87.0> Supervisor {<0.87.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.88.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 15:24:00.496 [error] <0.60.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[rabbit_farms,{stop,normal},{state,initialized},{{badrecord,rabbit_farm},[{rabbit_farms,terminate,2,[{file,"src/rabbit_farms.erl"},{line,206}]},{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1031}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]},{{badrecord,rabbit_farm},[{rabbit_farms,terminate,2,[{file,"src/rabbit_farms.erl"},{line,206}]},{rabbit_farms,handle_call,3,[{file,"src/rabbit_farms.erl"},{line,107}]},{gen_server2,handle_msg,2,[{...},...]},...]}]},...}}
2013-07-02 15:46:36.257 [error] <0.60.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[rabbit_farms,{stop,normal},{state,initialized},{{badrecord,rabbit_farm},[{rabbit_farms,terminate,2,[{file,"src/rabbit_farms.erl"},{line,206}]},{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1031}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]},{{badrecord,rabbit_farm},[{rabbit_farms,terminate,2,[{file,"src/rabbit_farms.erl"},{line,206}]},{rabbit_farms,handle_call,3,[{file,"src/rabbit_farms.erl"},{line,107}]},{gen_server2,handle_msg,2,[{...},...]},...]}]},...}}
2013-07-02 15:46:50.009 [error] <0.60.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[rabbit_farms,{stop,normal},{state,initialized},{{badrecord,rabbit_farm},[{rabbit_farms,terminate,2,[{file,"src/rabbit_farms.erl"},{line,206}]},{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1031}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]},{{badrecord,rabbit_farm},[{rabbit_farms,terminate,2,[{file,"src/rabbit_farms.erl"},{line,206}]},{rabbit_farms,handle_call,3,[{file,"src/rabbit_farms.erl"},{line,107}]},{gen_server2,handle_msg,2,[{...},...]},...]}]},...}}
2013-07-02 15:47:03.336 [error] <0.132.0> gen_server <0.132.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.140.0>,killed}, {state,#Port<0.3815>,600,<0.136.0>,131072,undefined,false}) line 58
2013-07-02 15:47:03.337 [error] <0.132.0> CRASH REPORT Process <0.132.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.140.0>,killed}, {state,#Port<0.3815>,600,<0.136.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 15:47:03.341 [error] <0.131.0> Supervisor {<0.131.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.132.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.140.0>,killed}, {state,#Port<0.3815>,600,<0.136.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 15:47:03.344 [error] <0.131.0> Supervisor {<0.131.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.132.0> exit with reason reached_max_restart_intensity in context shutdown
2013-07-02 15:47:33.751 [error] <0.188.0> gen_server <0.188.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.196.0>,killed}, {state,#Port<0.3965>,600,<0.192.0>,131072,undefined,false}) line 58
2013-07-02 15:47:33.753 [error] <0.188.0> CRASH REPORT Process <0.188.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.196.0>,killed}, {state,#Port<0.3965>,600,<0.192.0>,131072,undefined,false}) line 58 in gen_server:terminate/6 line 747
2013-07-02 15:47:33.756 [error] <0.187.0> Supervisor {<0.187.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.188.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.196.0>,killed}, {state,#Port<0.3965>,600,<0.192.0>,131072,undefined,false}) line 58 in context child_terminated
2013-07-02 15:47:33.759 [error] <0.187.0> Supervisor {<0.187.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(amqp_network_connection, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"192.168.3.202",5672,0,0,0,infinity,none,[#Fun<..>,...],...}, #Fun<amqp_connection_sup.0.55585968>, #Fun<amqp_connection_sup.2.55585968>, []) at <0.188.0> exit with reason reached_max_restart_intensity in context shutdown
